import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.join(process.cwd(), ".env") });

export default {
	node_env: process.env.NODE_ENV,
	port: process.env.PORT,
	database_url: process.env.DATABASE_URL,
	direct_url: process.env.DIRECT_URL,
	app_url: process.env.APP_URL,
	bcrypt_salt_rounds: process.env.BCRYPT_SALT_ROUNDS,
	jwt_access_secret: process.env.JWT_ACCESS_SECRET!,
	jwt_refresh_secret: process.env.JWT_REFRESH_SECRET!,
	jwt_access_expires_in: process.env.JWT_ACCESS_EXPIRES_IN!,
	jwt_refresh_expires_in: process.env.JWT_REFRESH_EXPIRES_IN!,
	GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
	GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
	GOOGLE_CLIENT_CALLBACK_URL: process.env.GOOGLE_CLIENT_CALLBACK_URL!,
	redis_user: process.env.REDIS_USER!,
	redis_password: process.env.REDIS_PASSWORD!,
	redis_host: process.env.REDIS_HOST!,
	redis_port: process.env.REDIS_PORT!,
	smtp_user: process.env.SMTP_USERNAME!,
	smtp_password: process.env.SMTP_PASSWORD!,
	email_sender: process.env.EMAIL_SENDER!,
	// Seed credentials
	super_admin_name: process.env.SUPER_ADMIN_NAME,
	super_admin_email: process.env.SUPER_ADMIN_EMAIL,
	super_admin_password: process.env.SUPER_ADMIN_PASSWORD,
	tester_admin_name: process.env.TESTER_ADMIN_NAME,
	tester_admin_email: process.env.TESTER_ADMIN_EMAIL,
	tester_admin_password: process.env.TESTER_ADMIN_PASSWORD,
	tester_driver_name: process.env.TESTER_DRIVER_NAME,
	tester_driver_email: process.env.TESTER_DRIVER_EMAIL,
	tester_driver_password: process.env.TESTER_DRIVER_PASSWORD,
	tester_dispatcher_name: process.env.TESTER_DISPATCHER_NAME,
	tester_dispatcher_email: process.env.TESTER_DISPATCHER_EMAIL,
	tester_dispatcher_password: process.env.TESTER_DISPATCHER_PASSWORD,
	tester_hospital_staff_name: process.env.TESTER_HOSPITAL_STAFF_NAME,
	tester_hospital_staff_email: process.env.TESTER_HOSPITAL_STAFF_EMAIL,
	tester_hospital_staff_password: process.env.TESTER_HOSPITAL_STAFF_PASSWORD,
	frontend_url: process.env.FRONTEND_URL ?? "http://localhost:3000",
	ssl_commerz_store_id: process.env.SSL_COMMERZ_STORE_ID,
	ssl_commerz_store_passwd: process.env.SSL_COMMERZ_STORE_PASSWORD,
};
